### ISSUE TITLE
Chinese characters can not be properly shown

### ISSUE THREAD

**Issue by Ptilopsis01** [maximegmd/CyberEngineTweaks#936] opened 2024-03-17 03:23 UTC
# README

Github is NOT here for support and general questions, it's designed for developers to discuss development and code. If your issue is unrelated to anything technical, do not make an issue, you will be blocked and your issue closed without an answer.

# Bug

Operating system: win11
Game version: 2.12
CET version: 1.31.3
GPU: rtx3060m

## Description

![image](https://github.com/maximegmd/CyberEngineTweaks/assets/93318731/91fdde33-b187-4f9c-96f4-f1c01a9d853e)
You can see many "?" in this picture, which are all common Chinese characters that can not be shown correctly.

## Expected behaviour

Show Chinese characters correctly

## Reproduction

Download and install a mod using CET with Chinese characters.

**Comment by maximegmd** [comment] 2024-03-17 09:52
Could you give us example characters that we can use to test and reproduce? None of us know Chinese so that would help us a ton :)

**Comment by Ptilopsis01** [comment] 2024-03-17 12:53
> Could you give us example characters that we can use to test and reproduce? None of us know Chinese so that would help us a ton :)

The characters missing in this pictures are “狙” “瞄” “刹”. I doubt it's the problem of the used font

**Comment by WSSDude** [comment] 2024-04-04 19:51
Yeah, default ImGui glyph ranges are incomplete (and hog a lot of memory unnecessarily).

We had #840 previously merged, but reverted it due to issues with ImGui, specifically we are waitting for this PR to push it forward https://github.com/ocornut/imgui/pull/3761

I would rather not start extending the ranges manually, the PR above includes glyph ranges builder which should be resolving glyphs as they appear, being more optimal and universal.

**Comment by Nats-ji** [comment] 2024-07-01 22:33
编辑cet安装目录里面的`configs.json`把`language`那一项的内容改成`ChineseFull`

**Comment by Ptilopsis01** [comment] 2024-07-08 19:34
> 编辑cet安装目录里面的`configs.json`把`language`那一项的内容改成`ChineseFull`

是config.json吗？改了之后好像还是一样的现象，还是有很多字符是显示的?

**Comment by Ptilopsis01** [comment] 2024-08-25 13:07
感谢，确实可以了

**Closed** 2024-08-25 13:08 UTC
Labels: bug
