### ISSUE TITLE
AMD Platform Crashes after changing Graphics Settings

### ISSUE THREAD

**Issue by CloudBank-3055** [maximegmd/CyberEngineTweaks#879] opened 2023-10-07 11:16 UTC
# Bug

Operating system: Windows 11 （22621.2361）
Game version: 2.01
CET version: v1.27.0 (EDIT:v1.27.1 has same problem)
GPU: AMD Radeon RX 5700

## Description
After using fast travel (whether provided by the game itself or any other mod), changing any graphics settings (Such as FSR settings, resolution, HDR switch) will cause inoperability, black screen, game crash and graphics driver crash. After testing the control variable method, it was found that everything could be restored to normal simply by removing the CET mod.

## Expected behaviour

No longer crash after changing graphics settings

## Reproduction

1. Install CET mod
2. Load any save file
3. Open AMD readon overlays to monitor such as FPS / GPU UTIL / VRAM / etc. 
4. Use any fast travel point to any other place
5. Open game settings, change any of the options in the Graphics or Video tab (Such as FSR settings, resolution, HDR switch)
6. Press APPLY button
7. Crash happens.

EDIT: I found that without Step 3 and 4 , it would also cause a crash

Here are some crash reports and log, including game itself and CET's
[Cyberpunk2077_CrashReports.zip](https://github.com/maximegmd/CyberEngineTweaks/files/12837591/Cyberpunk2077_CrashReports.zip)

[ManualSave-1.zip](https://github.com/maximegmd/CyberEngineTweaks/files/12837604/ManualSave-1.zip)

**Comment by WSSDude** [comment] 2024-07-31 16:26
Other overlays are known to cause various problems, including some monitoring software and antiviruses. Nit much that can be done, although it shoukd be more stable once ImGui fixes font updating and we rebase onto it, should solve multiple issues related to swapchain resets.

Closing this as this is partially a duplicate of #911 which may resolve some of these issues. ImGui just has to get fixed first as nobody is going to keep patches alive in the CET itself...

**Closed by WSSDude** 2024-07-31 16:26 UTC
