### ISSUE TITLE
Buttons unclickable: apparent scaling issue when running non-native monitor resolution fullscreen with CET 1.34.0 and patch 2.2

### ISSUE THREAD

**Issue by Seneca-lives** [maximegmd/CyberEngineTweaks#978] opened 2024-12-11 17:29 UTC
# Bug

Operating system:  Windows 11
Game version: 2.2
CET version: 1.34.0
GPU: RTX 3080 Ti

## Description

When running the game fullscreen in a non-native resolution (e.g. 1440p on a 4K monitor), CET buttons don't activate on mouseover/mouseclick. With some searching, the "activation area" for the buttons can be found elsewhere on the screen. This does not happen in Windowed/Windowed Borderless mode, where the 1440p window only occupies part of the 4K monitor.

**Comment by WSSDude** [comment] 2024-12-11 17:49
This is most likely some other mod using CET bug. We had seen similar reports on Discord in the past and it was always some mod moving other windows offscreen due to error.

Try to clean CET mods folder (is enough to rename it to mods.bak or simliar for testing purposes) and remove layout.ini.

If the problem persists with just CET and no other mods inside CET, feel free to reopen. Closing this for now as this seems to be invalid.

**Comment by WSSDude** [comment] 2024-12-11 17:52
Note that it is not enough to disable mods in the Nexus Mod Manager or similar, you have to manually clean the folder, mod managers like to keep leftovers for some reason sometimes.

Try the steps mentioned before reopening.

**Comment by WSSDude** [comment] 2024-12-11 17:56
Actually wait I misread the issue, this may be some bug in the end... But still please try what I wrote, _maybe_ it is related somewhat...

**Comment by Seneca-lives** [comment] 2024-12-11 17:58
Thanks, but just tested it on a clean install, only CET and no other mods, and got the same issue in 1440p.

**Comment by WSSDude** [comment] 2024-12-11 18:00
Let me check real quick, it may be related to @dragonzkiller ImGui update.

**Comment by WSSDude** [comment] 2024-12-11 18:02
Yep can reproduce, will try to fix it real quick.

**Comment by WSSDude** [comment] 2024-12-11 18:36
Could you just quickly test with the artifact from this action?

I'm going to try to fix it in the meantime but it may not be as quick as trying to utilize this... It should not affect any mods atm as none should really be using the new features atm.

https://github.com/maximegmd/CyberEngineTweaks/actions/runs/12282469466/artifacts/2307542673

**Comment by Seneca-lives** [comment] 2024-12-11 18:57
That solved it for me! (Also tested it with a few mods.)

**Comment by WSSDude** [comment] 2024-12-11 19:15
I have a real fix now I believe also, now just to wait for yamashi. Issue should autoclose once it gets merged.

**Comment by Nylon1s** [comment] 2024-12-11 19:26
Same issue. 

When I tried to change the screen resolution, the actual position of the cursor was not taken into.

Operating system: Windows 11
Game version: 2.2
CET version: 1.34.0
GPU: RTX 3060 Ti

**Comment by WSSDude** [comment] 2024-12-11 19:30
Just get this as I wrote above you...

https://github.com/maximegmd/CyberEngineTweaks/actions/runs/12283289827/artifacts/2307809494

There should be some release soon.

**Comment by Nylon1s** [comment] 2024-12-11 19:36
Solved! Tested with all mods installed. Doesn't detected any other issues.
Thank you, wise man! ♥️

**Closed** 2024-12-12 10:54 UTC
Labels: bug
