### ISSUE TITLE
CET menus scaling issue with DLSS in Fullscreen

### ISSUE THREAD

**Issue by G3ch0** [maximegmd/CyberEngineTweaks#981] opened 2024-12-12 18:16 UTC
# Bug

menu scaling issue with DLSS in Fullscreen causing menu prompts to be misaligned

Operating system: Windows 11
Game version: 2.2
CET version: 1.34.0
GPU: 3070

## Description

There seems to be an issue with the new version not scaling menus properly with DLSS in Fullscreen. Causing menu interactions to be significantly far away from the actual menu itself. Switching to windowed mode fixes this which leads me to believe it is a scaling issue. I don't believe this is an issue on my end as I have reinstalled CET and the issue persisted. I also used the old version on 2.13 of Cyberpunk and couldn't reproduce the issue there. So seems limited to 1.34.0 CET and 2.2 Cyberpunk.

## Expected behaviour

Menu prompts to align with actual menu interaction.

## Reproduction

Boot game in Fullscreen with DLSS enabled (I was using balanced). Open CET and try to interact with menus. You should find the menu seems to be non interactable, but moving the mouse around you will see some menu prompts highlight despite the mouse not being over them.

**Comment by WSSDude** [comment] 2024-12-12 18:29
Duplicate of #978, already fixed, just not yet released.

**Closed by WSSDude** 2024-12-12 18:29 UTC
