### ISSUE TITLE
Crash if alt-tabbed with console window open.

### ISSUE THREAD

**Issue by Amariithynar** [maximegmd/CyberEngineTweaks#867] opened 2023-09-29 19:47 UTC
Latest game build, latest CET; alttabbing causes the game to flatline if console is open. If console is closed using the preset key, can alt-tab infinite number of times no issue. Happens 100% of the time. Unsure if related to drivers or no (running a 2060 with latest game drivers, so doubt it, but can never be sure).

**Comment by WSSDude** [comment] 2023-09-30 10:18
Think this may be related to #868 or #850 .

Its either new driver for some reason being too picky or maybe its just ImGui acting up... Former being #868 and latter being #850. if you confirm one or the other, just make comment there i guess and close this so there are not multiple issues with same problem.

**Closed** 2023-10-01 05:16 UTC

**Comment by Amariithynar** [comment] 2023-10-02 10:53
> Think this may be related to #868 or #850 .
> 
> Its either new driver for some reason being too picky or maybe its just ImGui acting up... Former being #868 and latter being #850. if you confirm one or the other, just make comment there i guess and close this so there are not multiple issues with same problem.

Not likely related to #868 . Game runs just fine. It's only when alt-tabbing *with console open* that it flatlines, specifically, and it happens with a 100% reproduction rate, using CET v1.26.1. Game works just fine otherwise, CET also otherwise works just fine; I just need to make sure I don't have the console open when I alt-tab, or it causes an immediate crash. *shrug*

Definitely not related to #850 because it's an nvidia GPU (I did state it's a 2060) and, as stated, game runs just fine otherwise, for hours at a time (even had it alt-tabbed in the background for hours after playing for some time, then alt-tabbed back and resumed play later, with no issues).

**Comment by WSSDude** [comment] 2023-10-02 11:44
#850 is not AMD exclusive i think that is your issue from what you wrote.

**Comment by WSSDude** [comment] 2023-10-02 11:44
Just happens most often with AMD gpus...

**Comment by Amariithynar** [comment] 2023-10-07 16:15
> #850 is not AMD exclusive I think that is your issue from what you wrote.

#850 is about a crash due to changing visuals, though? Game and PC settings are the same for visuals and I'm not changing any visuals, it's just alt-tabbing when CET console is open that causes a crash (specifically, if I click on anything afterwards; I can still alt-tab back into game so long as I do not click anything else, be it an open notepad or opening a new program via taskbar or just clicking on desktop).

**Comment by WSSDude** [comment] 2023-10-07 17:09
Device reset caused by alt+tab or changes to resolution etc. end up in same type of crash. ImGui resource handling is improper, we also wrongly work with AddTexture...
This is why I say they are the same, you dont see the lower level of what is going on...

**Comment by Amariithynar** [comment] 2023-10-08 14:28
> Device reset caused by alt+tab or changes to resolution etc. end up in same type of crash. ImGui resource handling is improper, we also wrongly work with AddTexture... This is why I say they are the same, you dont see the lower level of what is going on...

Ah, so you're looking at it from a "this is the same/similar final cause of the crash" perspective ("it's caused by ImGui resource handling so we won't touch it"), while I'm looking at it from a "these are two wildly different causes" perspective, where the issue could be resolved fairly simply, as far as I see it (eg. force-close console when alt-tabbed).
