### ISSUE TITLE
Crash on AMD GPUs with Vsync enabled

### ISSUE THREAD

**Issue by honey-sorry-i-ate-a-bus** [maximegmd/CyberEngineTweaks#850] opened 2023-09-15 17:51 UTC
Like the title says, the game with CET installed will crash if you have vsync enabled. 

Steps to reproduce: 
 
0. Fresh CP2077 (GOG) install
1. Fresh CET install
2. Go to game settings
3. Enable vsync, apply
4. Change resolution
5. Apply
6. Get crash

Tested on RX 400, 500 and 6000 series. Regardless of GPU driver version the outcome is the same. The game will crash with the probability of 100%.

The game will also occasionally crash if you change the DRS resolution sliders values (these crashes are inconsistent).

Never tested on nVidia GPUs. 

System specs: 

Rocket Lake CPU (both Engineering Sample CPU and a "normal" i5-11600K behave the same)
Z490 Vision D
16 GB DDR4 (Dual channel)
ReBAR is enabled.
Windows 10 21H2, Windows 10 22H2, Windows 11 22H2.

**Comment by WSSDude** [comment] 2023-09-15 19:07
Could you try build from this action? (download the artifact zip archive at the bottom)

https://github.com/maximegmd/CyberEngineTweaks/actions/runs/5626293103

**Comment by WSSDude** [comment] 2023-09-15 19:12
If it works with the build, please leave a note in #840 that it fixed your issue.

**Comment by honey-sorry-i-ate-a-bus** [comment] 2023-09-15 19:25
> If it works with the build, please leave a note in #840 that it fixed your issue.

It does not.

**Comment by maximegmd** [comment] 2023-09-27 08:24
Marking as wontfix, we can't fix the AMD drivers sadly.

**Closed by maximegmd** 2023-09-27 08:24 UTC
Labels: wontfix

**Comment by WSSDude** [comment] 2023-09-27 08:49
Have to disagree a bit, this is fixable for sure. I would keep this opened just so we can reference some issue if nothing else, we should be able to fix it at some point when ImGui has proper font management and we fix hiw we handle AddTexture.

But it is ultimately your call I guess... Can keep this in mind I believe.

**Comment by WSSDude** [comment] 2023-10-07 17:07
Device reset caused by alt+tab or changes to resolution etc. end up in same type of crash. ImGui resource handling is improper, we also wrongly work with AddTexture...
This is why I say they are the same, you dont see the lower level of what is going on...
