### ISSUE TITLE
new event for CET Menu and on draw

### ISSUE THREAD

**Issue by notaspirit** [maximegmd/CyberEngineTweaks#972] opened 2024-11-04 09:15 UTC
Currently every mod that uses a CET overlay has to check if the overlay is open or not every single frame. (assuming it's not an always on overlay which it isn't for most most mods). 

This seems very inefficient and wasteful of cpu resources, even if it may only have a minor effect on performance. 

Proposed improvement: 
add a new event that fires every frame just like onDraw, but only if the overlay is open. 
It's not supposed to replace already existing events, as that would break backwards compatability.

**Comment by WSSDude** [comment] 2024-12-05 10:10
Effectively duplicate of #490

**Closed by WSSDude** 2024-12-05 10:10 UTC

**Comment by WSSDude** [comment] 2024-12-05 11:30
If you have some ideas, Id add it there. Or we can keep this open and I can copy later stuff from there, I wrore it rather quickly. But the idea was pretty much on-par with what you wanted I believe.
